[project]
name = "genaiprojects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio>=6.2.0",
    "torch>=2.9.1",
    "transformers>=4.57.3",
    "youtube-transcript-api>=1.2.3",
]
